version: '3'

services: 
  destify-fullstack:
    depends_on:
      - moviesdb
    build: 
      context: .
      dockerfile: Dockerfile
    image: destify-fullstack
    container_name: destify-fullstack
    restart: always 
    ports:
      - "3000:3000"  # Backend port
      - "3001:3001"  # Frontend port
    environment:
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      PORT: 3000  # Backend port
      FRONTEND_PORT: 3001  # Frontend port
      NEXT_PUBLIC_API_BASE_URL: http://localhost:3000  # Frontend API base URL
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: ${NODE_ENV}

  moviesdb:
    image: postgres:14.3
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment: 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
    container_name: moviesdb